# Generated by Django 5.0.2 on 2024-02-28 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_airline_flight_runway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runway',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='core.airport'),
        ),
    ]
